isa-l_crypto: Add submodule
Signed-off-by: Alexey Marchuk <alexeymar@nvidia.com>
Change-Id: I9cf6b754fb3888e21c05aa20bade21cf90d5d090

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -51,8 +51,8 @@ function usage() {
 	echo "                           Implies --without-dpdk."
 	echo " --with-idxd               Build the IDXD library and accel framework plug-in module."
 	echo " --without-idxd            Disabled while experimental. Only built for x86 when enabled."
-	echo " --with-crypto             Build vbdev crypto module."
-	echo " --without-crypto          No path required."
+	echo " --with-crypto             Build isa-l-crypto and vbdev crypto module. No path required."
+	echo " --without-crypto          Disable isa-l-crypto and vbdev crypto module."
 	echo " --with-fio[=DIR]          Build fio_plugin."
 	echo " --without-fio             default: /usr/src/fio"
 	echo " --with-vhost              Build vhost target. Enabled by default."
@@ -1077,6 +1077,18 @@ if [[ $arch == x86_64* ]] || [[ $arch == aarch64* ]]; then
 			echo "WARNING: ISA-L & DPDK crypto cannot be used as nasm ver must be 2.14 or newer."
 		fi
 	fi
+	# check gas version on aarch64
+	if [[ $arch == aarch64* ]]; then
+		ver=$(as --version 2> /dev/null | awk 'NR==1{print $7}')
+		if lt "$ver" 2.24; then
+			# ISA-L, compression & crypto require gas version 2.24 or newer.
+			CONFIG[ISAL]=n
+			echo "Notice: ISA-L, compression & crypto require GAS version 2.24 or newer. Turning off default ISA-L and crypto features."
+		elif lt "$ver" 2.34; then
+			#For gas v2.24~v2.34, sve2 instructions are not supported. To workaround it, sve2 optimization should be disabled
+			ISAL_CRYPTO_OPTS+=("--disable-sve2")
+		fi
+	fi
 else
 	# for PPC
 	CONFIG[ISAL]=n
@@ -1102,6 +1114,26 @@ else
 	echo "so these features will be disabled."
 	CONFIG[CRYPTO]=n
 	CONFIG[REDUCE]=n
+fi
+if [[ "${CONFIG[CRYPTO]}" = "y" ]]; then
+	if [ ! -f "$rootdir"/isa-l-crypto/autogen.sh ]; then
+		echo "ISA-L-crypto is required but was not found, please init the submodule with:"
+		echo "  git submodule update --init"
+		echo "and then re-run this script."
+		exit 1
+	fi
+
+	cd $rootdir/isa-l-crypto
+	ISAL_CRYPTO_LOG=$rootdir/isa-l-crypto/spdk-isal-crypto.log
+	if [[ -n "${CONFIG[CROSS_PREFIX]}" ]]; then
+		ISAL_CRYPTO_OPTS+=("--host=${CONFIG[CROSS_PREFIX]}")
+	fi
+	ISAL_CRYPTO_OPTS+=("--enable-shared=no")
+	echo -n "Configuring ISA-L-crypto (logfile: $ISAL_CRYPTO_LOG)..."
+	./autogen.sh &> $ISAL_CRYPTO_LOG
+	./configure CFLAGS="-fPIC -g -O2" "${ISAL_CRYPTO_OPTS[@]}" >> $ISAL_CRYPTO_LOG 2>&1
+	echo "done."
+	cd $rootdir
 fi
 
 if [[ "${CONFIG[SMA]}" = "y" ]]; then
